version: "3.8"

services:
#  app:
#    build: .
#    env_file:
#      - .env
#    ports:
#      - "${HTTP_PORT}:${HTTP_PORT}"
#    depends_on:
#      - postgres
#    restart: unless-stopped

  postgres:
    image: postgres
    volumes:
      #- pg-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    ports:
      - "5433:5432"
    restart: unless-stopped

#volumes:
#  pg-data: